apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 3  # Number of desired replicas (you can adjust this value)
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: my_e_cards_app:latest
          ports:
            - containerPort: 3000  # Port number of your React app